{% set name = "pysuerga" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae11f38d5d6d7a47cfa5661f3782370e04431cda4e4b2b526f23d8a19447dfcb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - markdown
    - jinja2
    - pyyaml
    - feedparser

test:
  imports:
    - pysuerga
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/datapythonista/pysuerga
  summary: Python simple static site generator for open source projects
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
